# Generated by Django 4.1.6 on 2023-02-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0002_delete_newses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_Headline', models.CharField(max_length=255)),
                ('news_date', models.DateField()),
                ('news_author', models.CharField(max_length=255)),
                ('news_description', models.CharField(max_length=1000)),
                ('news_Link_Text', models.CharField(max_length=255)),
                ('news_Text_Link', models.CharField(max_length=1000)),
                ('news_image', models.ImageField(upload_to='img/%y')),
            ],
        ),
    ]
