# Generated by Django 4.1.6 on 2023-02-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0004_galleryheading_gallerymoreimage_gallerysliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_Heading', models.CharField(max_length=255)),
                ('about_Description', models.CharField(max_length=1000)),
                ('about_Management_Heading', models.CharField(max_length=255)),
                ('about_Management_SubHeading', models.CharField(max_length=255)),
                ('about_Management_Description_P1', models.CharField(max_length=1000)),
                ('about_Management_Description_P2', models.CharField(max_length=1000)),
                ('about_Management_Description_P3', models.CharField(max_length=1000)),
                ('about_Management_Image', models.ImageField(upload_to='img/%y')),
                ('about_Video_Heading', models.CharField(max_length=255)),
                ('about_Video_Description_P1', models.CharField(max_length=1000)),
                ('about_Video_Description_P2', models.CharField(max_length=1000)),
                ('about_Video', models.FileField(upload_to='img/%y')),
            ],
        ),
    ]
