# Generated by Django 4.1.6 on 2023-02-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0005_aboutdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_Heading', models.CharField(max_length=255)),
                ('contact_Map_Heading', models.CharField(max_length=255)),
            ],
        ),
    ]
